### ISSUE TITLE
Create contest page

### ISSUE THREAD

**Issue by stecko1980** [hzxie/voj#102]
I can't create contest via user's interface
![image](https://user-images.githubusercontent.com/67151586/104157583-17b81e00-53f4-11eb-8067-90ff8b50bea4.png)
Also I can't see all contest via admin page
![image](https://user-images.githubusercontent.com/67151586/104157688-4e8e3400-53f4-11eb-949b-6e94c9a786df.png)

**Comment by hzxie** [comment]
It has not been implemented yet.
