### ISSUE TITLE
How we can help you with translate?

### ISSUE THREAD

**Issue by stecko1980** [hzxie/voj#103]

**Comment by hzxie** [comment]
You can simply translate the following file.

https://github.com/hzxie/voj/blob/master/web/src/main/resources/localization/voj_en_US.properties

**Comment by stecko1980** [comment]
And if we want to contribute VOJ, how we can give you translated file?

**Comment by hzxie** [comment]
You can create a pull request [here](https://github.com/hzxie/voj/pulls).
Before creating a pull request, you need to fork the project.
If you are not familiar with `git`, you can send the file to cshzxie@gmail.com

Thanks for your contribution.

**Comment by stecko1980** [comment]
Ok. And how set default locale?

**Comment by hzxie** [comment]
The default locale is determined by your browser preferences.
Regarding to adding new locales, I will do it for you after you submitting the translated file.
