### ISSUE TITLE
How can I prohibit a participant from sending the same code several times?

### ISSUE THREAD

**Issue by stecko1980** [hzxie/voj#104]
How can I prohibit a participant from sending the same code several times?

**Comment by hzxie** [comment]
What do you mean? I don't understand.

**Comment by stecko1980** [comment]
We want to start contest on VOJ and we want to secure from DDoS and we want that contestant can't send one program code several times.

**Comment by hzxie** [comment]
The whole system is protected by CSRF. 
I think the code may not be submitted several times.

**Comment by stecko1980** [comment]
Yes, we know about CSRF. But we want that contestant can't send 2 or more time same code, becouse we want to use it in our school where pupils DDoS our site.

**Comment by hzxie** [comment]
But the button is disabled after submitting. How to submit the code more than once?
One solution is to compare the code with the previous ones. If the newly submitted code is the same as the previous one, ignore the code.
What do you think?

**Comment by stecko1980** [comment]
The contestant can publish a partial solution and throw it several times and because of this voj.judger may not work (collapse)

**Comment by stecko1980** [comment]
I have edited SubmissionService.java but can't compile(error)
SubmissionService.java:
```
private Map<String, ? extends Object> getSubmissionCreationResult(Submission submission, boolean isCsrfTokenValid) {
		Map<String, Boolean> result = new HashMap<>(6, 1);
		String code = submission.getCode();
		List submissionsofthisuser = getSubmissions(submission.getProblem(), submission.getUser().getUsername());
		Boolean isCodeLikePrevious = false;
		for (Submission submissionp : submissionsofthisuser){
			if(submissionp.getCode() == code){ isCodeLikePrevious = true; break;}
		}
		result.put("isUserLogined", submission.getUser() != null);
		result.put("isProblemExists", submission.getProblem() != null);
		result.put("isLanguageExists", submission.getLanguage() != null);
		result.put("isCodeEmpty", code == null || code.length() == 0);
		result.put("isCsrfTokenValid", isCsrfTokenValid);
		result.put("isCodeLikePrevious", isCodeLikePrevious);
		boolean isSuccessful = result.get("isUserLogined")	&&  result.get("isProblemExists") &&
							   result.get("isLanguageExists") && !result.get("isCodeEmpty")	 &&
							   result.get("isCsrfTokenValid") && !result.get("isCodeLikePrevious");
		result.put("isSuccessful", isSuccessful);
		return result;
	}
```

**Comment by hzxie** [comment]
Please provide the corresponding logs.

**Comment by hzxie** [comment]
Closed due to the inactivity.
