### ISSUE TITLE
报错UnsatisfiedLinkError

### ISSUE THREAD

**Issue by LyamAL** [hzxie/voj#108]
按照readme一步一步来的， 但还是这个错误>.<!!!

LOGS：
[WARN] 2021-02-16 15:26:36,093 [main] org.springframework.context.support.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationDispatcher': Unsatisfied dependency expressed through field 'judgerDispatcher'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dispatcher': Unsatisfied dependency expressed through field 'compiler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'compiler': Unsatisfied dependency expressed through field 'compilerRunner'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'runner' defined in URL [jar:file:/D:/mystuff/voj-master/voj-master/judger/target/voj.judger.jar!/org/verwandlung/voj/judger/core/Runner.class]: Instantiation of bean failed; nested exception is java.lang.**UnsatisfiedLinkError**: **C:\Users\ZAQ\AppData\Local\Temp\JudgerCore10909925940901070683.dll: 找不到指定的程序。**

**Comment by LyamAL** [comment]
不过新年快乐哦

**Comment by hzxie** [comment]
Refer to #105 and other previous issues.
