### ISSUE TITLE
关于不同编程语言编译器的调用问题

### ISSUE THREAD

**Issue by BingCUMaO** [hzxie/voj#112]
你好，请问这个Judge部分是如何调用编译Pascal和Ruby语言的呢？在跟踪unix部分的Judger.Core.Runner.cpp中的getRuntimeResult方法，我发现程序在编译的时候是执行的execvp()这个方法，所以程序应该是通过环境编译文件的，然而我在Judge部分的Dockerfile中看到的是，注释“# Setup Compliers”下面只安装了一个py3环境，在dockerfile中甚至没有看到Pascal和Ruby的相关环境安装。

**Comment by hzxie** [comment]
Yes, we don't install Pascal and Ruby in Dockerfile. You can install it by yourself.
After the installation, you can update the `Language Settings` on the administration page.

![Screenshot from 2021-04-11 15-13-02](https://user-images.githubusercontent.com/1730504/114295549-7a46b600-9ad8-11eb-9410-eb7d061ccdaf.png)
