### ISSUE TITLE
JudgerCore报错，需要自己重新打包吗？没有JudgerCore.dll文件

### ISSUE THREAD

**Issue by suixin837** [hzxie/voj#115]
我运行项目，会一直报错，找不到JudgerCore类库，应该如何解决呢

**Comment by hzxie** [comment]
Please provide more information

**Comment by suixin837** [comment]
win10 64



在 2021-04-25 12:44:20，"Haozhe Xie" ***@***.***> 写道：

Please provide more information

操作系统版本？

**Comment by suixin837** [comment]
控制台会出现一下错误，因为乱码我也不清楚是哪里的问题，根据错误码提示的话是说参数错误
![image](https://user-images.githubusercontent.com/33931089/115987997-2b297680-a5ea-11eb-8c36-15fb0b78459e.png)
