### ISSUE TITLE
CreateProcess with ErrorCode 0 for Windows 10

### ISSUE THREAD

**Issue by suixin837** [hzxie/voj#116]
![image](https://user-images.githubusercontent.com/33931089/116039652-96805080-a69d-11eb-87ad-10909ea3bd74.png)

**Comment by hzxie** [comment]
请先解决乱码的问题。

**Comment by hzxie** [comment]
Please also provide more information about your JDK version and OS version.

**Comment by suixin837** [comment]
乱码问题如何解决 我试过了 无论怎么设置编码，都是乱码  
jdk1.8   win10  64

**Comment by hzxie** [comment]
我自己用的英文版操作系统 我不知道怎么解决乱码问题。
本质上是因为中文版Windows使用GBK编码，但是我们的项目使用UTF-8编码。

**Comment by suixin837** [comment]
好的 我试着改下系统编码

**Comment by suixin837** [comment]
![image](https://user-images.githubusercontent.com/33931089/116046122-558c3a00-a6a5-11eb-902c-514fd470cd1a.png)
编码问题已解决 提示参数错误  我系统没有设置密码 所以system.username 和system.password为空 这个有影响吗

**Comment by hzxie** [comment]
你可以试一下加个密码？

**Comment by suixin837** [comment]
加上密码可以了 amazing！！但是如果我不设置密码 应如何处理呢

**Comment by hzxie** [comment]
造成错误的是使用了这个函数：

https://github.com/hzxie/voj/blob/9fe4dc3cd6284b04ffc8eaa9d6935c410c129b10/judger/src/main/cpp/windows/Judger.Core.Runner.cpp#L210-L213

改成CreateProcess应该就可以了，文档请参见：https://docs.microsoft.com/en-us/windows/win32/procthread/creating-processes
