### ISSUE TITLE
Tip: Convert into the spring boot application

### ISSUE THREAD

**Issue by maradanasai** [hzxie/voj#133]
I would be nice if you can convert the application into spring boot (spring reactive if possible) for better readability and maintenance

**Comment by hzxie** [comment]
Nice suggestion! However, there is no plan do to this.
If you are interested, you can submit a pull request.

**Comment by hzxie** [comment]
No. Every event can only be handled once.

**Comment by RajeevKumarMarrapu** [comment]
Ok. I think it is similar to RabbitMQ in terms of message delivery when multiple consumers are connected. How it will behave  when multiple instances of web is connected? Each web instance will listen all judger response events right (even for submission event not produced by that web instance)?
