### ISSUE TITLE
judger无法打包成功

### ISSUE THREAD

**Issue by zhoushi** [hzxie/voj#18]

**Comment by zhoushi** [comment]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.274 s
[INFO] Finished at: 2017-02-16T17:16:52+08:00
[INFO] Final Memory: 21M/213M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:
run (default) on project voj.judger: An Ant BuildException has occured: Execute
failed: java.io.IOException: Cannot run program "make": CreateProcess error=2, ?
????????
[ERROR] around Ant part ...<exec executable="make"></exec>... @ 13:27 in E:\proj
ect\voj\judger\target\antrun\build-jni.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE

**Comment by hzxie** [comment]
请在命令行下执行如下命令:

```
gcc -v
make
```

并给出输出结果, 谢谢.

**Comment by zhoushi** [comment]
已经打包成功了，mingw32-make.exe 忘记安装了
