### ISSUE TITLE
MacOS下make命令报错

### ISSUE THREAD

**Issue by nl101531** [hzxie/voj#19]
mkdir -p target/cpp
g++ -c -std=c++11 -Wall -fPIC -I "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/include" src/main/cpp/unix/Judger.Core.Runner.cpp -o target/cpp/Judger.Core.Runner.o
src/main/cpp/unix/Judger.Core.Runner.cpp:172:18: error: use of undeclared identifier 'sigtimedwait'
            if ( sigtimedwait(&sigset, NULL, &timeout) < 0 ) {
                 ^
src/main/cpp/unix/Judger.Core.Runner.cpp:306:31: error: use of undeclared identifier 'round'
    milliseconds            = round(spec.tv_nsec / 1.0e6);
                              ^
2 errors generated.
make: *** [target/cpp/Judger.Core.Runner.o] Error 1

mac下无法识别sigtimedwait这个函数,有空修复下不?个人对C不是很懂,所以无能为力了

**Comment by hzxie** [comment]
暂时不支持macOS哦~ 只支持Linux.

**Comment by hzxie** [comment]
This issue is about to close within 6 hours.
