### ISSUE TITLE
windows环境下judger打包问题，

### ISSUE THREAD

**Issue by zhoushi** [hzxie/voj#20]
jni:
     [echo] Generating JNI headers
     [exec] mkdir -p target/cpp
     [exec] Makefile:30: recipe for target 'target/cpp/Judger.Core.Runner.o' fai
led
     [exec] 命令语法不正确。
     [exec] make: *** [target/cpp/Judger.Core.Runner.o] Error 1
     [exec] Result: 2

gcc 和 make命令正常
谢谢博主了

**Comment by zhoushi** [comment]
![make](https://cloud.githubusercontent.com/assets/13301267/23448113/060ad2ba-fe8a-11e6-9c47-aac93c76dab3.jpg)

**Comment by hzxie** [comment]
你这个问题…… 我没法复现……
你在命令行里执行 `mkdir -p target/cpp` 提示什么?

**Comment by hzxie** [comment]
试着将 Makefile 中的第30行修改成 `mkdir target\cpp` 试试

**Comment by zhoushi** [comment]
改成mkdir target\cpp后打包结果
jni:
     [echo] Generating JNI headers
     [exec] mkdir target\cpp
     [exec] g++ -c -std=c++11 -Wall -fPIC -I "C:\Program Files\Java\jdk1.8.0_111
/include" src/main/cpp/windows/Judger.Core.Runner.cpp -o target/cpp/Judger.Core.
Runner.o
     [exec] g++ -fPIC -shared target/cpp/Judger.Core.Runner.o -luserenv -lpsapi
-o target/classes/JudgerCore.dll

...不知道对不对，然后根据博主命令启动jar包并启动web后发现消费者没有被消费
![queues](https://cloud.githubusercontent.com/assets/13301267/23489998/9e9c8892-ff30-11e6-89ba-26e331d7022a.jpg)

**Comment by hzxie** [comment]
构建成功了。
没有被消费，你启动judger了吗？

**Comment by zhoushi** [comment]
启动judger后报错

![default](https://cloud.githubusercontent.com/assets/13301267/23491612/4a220de6-ff3a-11e6-8702-33b4710c3806.jpg)

**Comment by zhoushi** [comment]
将jdk换成32位的然后启动judger过后消费者消费，但是出现如下错误，提交的题目一直处于pending中
event = SubmissionCreated
[INFO] 2017-03-02 12:03:29,615 [ActiveMQ Session Task-1] org.verwandlung.voj.judger.messenger.MessageReceiver - Received new submission task #1005
[INFO] 2017-03-02 12:03:30,655 [ActiveMQ Session Task-1] org.verwandlung.voj.judger.core.Compiler - Start compiling with command: javac D:/tmp/voj-1005/WGIfMDLCrFLH.java
▒▒▒▒ 02, 2017 12:03:30 ▒▒▒▒ org.springframework.jms.listener.SimpleMessageListenerContainer invokeErrorHandler
▒▒▒▒: Execution of JMS message listener failed, and no ErrorHandler has been set.
java.lang.UnsatisfiedLinkError: org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/util/Map;
        at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Native Method)
        at org.verwandlung.voj.judger.core.Runner.getRuntimeResult(Runner.java:148)
        at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:77)
        at org.verwandlung.voj.judger.core.Compiler.getCompileResult(Compiler.java:34)
        at org.verwandlung.voj.judger.core.Dispatcher.compile(Dispatcher.java:101)
        at org.verwandlung.voj.judger.core.Dispatcher.createNewTask(Dispatcher.java:60)
        at org.verwandlung.voj.judger.application.ApplicationDispatcher.onSubmissionCreated(ApplicationDispatcher.java:33)
        at org.verwandlung.voj.judger.messenger.MessageReceiver.newSubmissionHandler(MessageReceiver.java:53)
        at org.verwandlung.voj.judger.messenger.MessageReceiver.onMessage(MessageReceiver.java:32)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
        at org.springframework.jms.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:622)
        at org.springframework.jms.listener.SimpleMessageListenerContainer.processMessage(SimpleMessageListenerContainer.java:330)
        at org.springframework.jms.listener.SimpleMessageListenerContainer$2.onMessage(SimpleMessageListenerContainer.java:306)
        at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401)
        at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131)
        at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202)
        at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
        at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by hzxie** [comment]
请保证GCC的版本(x86, x64)和JDK的版本(x86, x64)是一致的。

**Comment by zhoushi** [comment]
版本一致了，大神可否加个好友但是还是出现上面的错误一直处于pending中，，，，，

**Comment by hzxie** [comment]
先执行`make clean`, 然后重新执行`mvn build`.

**Comment by zhoushi** [comment]
![default](https://cloud.githubusercontent.com/assets/13301267/23498947/f822378e-ff64-11e6-9a66-e64ec78c4efa.jpg)

$ mvn package -DskipTests
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building voj.judger 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ voj.judger ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ voj.judger ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 28 source files to E:\project\voj\judger\target\classes
[INFO]
[INFO] --- maven-antrun-plugin:1.7:run (default) @ voj.judger ---
[INFO] Executing tasks

jni:
     [echo] Generating JNI headers
     [exec] mkdir target\cpp
     [exec] g++ -c -std=c++11 -Wall -fPIC -I "C:/Program Files (x86)/Java/jdk1.8.0_121/include" src/main/cpp/windows/Judger.Core.Runner.cpp -o target/cpp/Judger.Core.Runner.o
     [exec] g++ -fPIC -shared target/cpp/Judger.Core.Runner.o -luserenv -lpsapi -o target/classes/JudgerCore.dll
[INFO] Executed tasks
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ voj.judger ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ voj.judger ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to E:\project\voj\judger\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ voj.judger ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ voj.judger ---
[INFO] Building jar: E:\project\voj\judger\target\voj.judger.jar
[INFO]
[INFO] --- maven-shade-plugin:2.4:shade (default) @ voj.judger ---
[INFO] Including org.springframework:spring-core:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.2 in the shaded jar.
[INFO] Including org.springframework:spring-tx:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-beans:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-orm:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-jdbc:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-jms:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-aop:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-context:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-expression:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-messaging:jar:4.3.5.RELEASE in the shaded jar.
[INFO] Including org.aspectj:aspectjrt:jar:1.8.10 in the shaded jar.
[INFO] Including org.aspectj:aspectjtools:jar:1.8.10 in the shaded jar.
[INFO] Including org.mybatis:mybatis:jar:3.4.2 in the shaded jar.
[INFO] Including org.mybatis:mybatis-spring:jar:1.3.0 in the shaded jar.
[INFO] Including org.mybatis.caches:mybatis-ehcache:jar:1.1.0 in the shaded jar.
[INFO] Including net.sf.ehcache:ehcache-core:jar:2.6.11 in the shaded jar.
[INFO] Including com.alibaba:druid:jar:1.0.27 in the shaded jar.
[INFO] Including mysql:mysql-connector-java:jar:5.1.40 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-spring:jar:5.14.2 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.13 in the shaded jar.
[INFO] Including org.apache.xbean:xbean-spring:jar:4.2 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-broker:jar:5.14.2 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-client:jar:5.14.2 in the shaded jar.
[INFO] Including org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1 in the shaded jar.
[INFO] Including org.fusesource.hawtbuf:hawtbuf:jar:1.11 in the shaded jar.
[INFO] Including org.apache.geronimo.specs:geronimo-j2ee-management_1.1_spec:jar:1.0.1 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-openwire-legacy:jar:5.14.2 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-pool:jar:5.14.2 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-jms-pool:jar:5.14.2 in the shaded jar.
[INFO] Including org.apache.geronimo.specs:geronimo-jta_1.0.1B_spec:jar:1.0.1 in the shaded jar.
[INFO] Including org.apache.commons:commons-pool2:jar:2.4.2 in the shaded jar.
[INFO] Including org.apache.directory.studio:org.apache.commons.io:jar:2.4 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.4 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-core:jar:2.5 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-api:jar:2.5 in the shaded jar.
[WARNING] aspectjrt-1.8.10.jar, aspectjtools-1.8.10.jar define 130 overlapping classes:
[WARNING]   - org.aspectj.internal.lang.reflect.SignaturePatternImpl
[WARNING]   - org.aspectj.runtime.reflect.SignatureImpl
[WARNING]   - org.aspectj.internal.lang.reflect.DeclareSoftImpl
[WARNING]   - org.aspectj.lang.reflect.AjType
[WARNING]   - org.aspectj.lang.annotation.control.CodeGenerationHint
[WARNING]   - org.aspectj.lang.JoinPoint$StaticPart
[WARNING]   - org.aspectj.runtime.internal.cflowstack.ThreadStackImpl11
[WARNING]   - org.aspectj.runtime.internal.cflowstack.ThreadStack
[WARNING]   - org.aspectj.internal.lang.reflect.InterTypeDeclarationImpl
[WARNING]   - org.aspectj.internal.lang.reflect.DeclareAnnotationImpl
[WARNING]   - 120 more...
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing E:\project\voj\judger\target\voj.judger.jar with E:\project\voj\judger\target\voj.judger-0.1.0-shaded.jar
[INFO] Dependency-reduced POM written at: E:\project\voj\judger\dependency-reduced-pom.xml
[INFO] Dependency-reduced POM written at: E:\project\voj\judger\dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.956 s
[INFO] Finished at: 2017-03-02T16:24:55+08:00
[INFO] Final Memory: 21M/68M
[INFO] ------------------------------------------------------------------------

jdk我也改成32位的了
![a](https://cloud.githubusercontent.com/assets/13301267/23499078/973015c6-ff65-11e6-86df-48e001f2a091.jpg)

**Comment by hzxie** [comment]
我觉得你应该把GCC换成64位的, 而不是把JDK换成32位的.

**Comment by zhoushi** [comment]
好的，谢谢博主，我试一试

**Comment by hzxie** [comment]
@zhoushi 
Have you fix the problem?

**Comment by zhoushi** [comment]
.......还没有，应该是我环境的原因，这两天没弄，应该不是bug你把这个issues给关了吧。。。
