### ISSUE TITLE
maven install卡在judger的ComparatorTest

### ISSUE THREAD

**Issue by oysakura** [hzxie/voj#23]
![default](https://user-images.githubusercontent.com/23307241/27435429-d248fc00-578e-11e7-8edd-40dfcc32d0eb.PNG)
本人在校学生,在学习jms和activemq,很多地方不懂,望dalao能在百忙中抽空解答.
我尝试不用测试生成了voj.jar,但是运行时要么显示没有显示,要么一堆异常,用binary版修改参数后也是一样.在测试时cpu和内存占用率都很高,还望dalao能在百忙中帮忙解答,谢谢.

**Comment by hzxie** [comment]
So 你这是解决了？
