### ISSUE TITLE
When I was doing mvn package for judger, something went wrong.

### ISSUE THREAD

**Issue by yrregnehc** [hzxie/voj#24]
![image](https://user-images.githubusercontent.com/29784649/27708456-012a5eda-5ce7-11e7-827a-a43dcd3fea94.png)

**Comment by hzxie** [comment]
Did you install `gcc` and add it to `PATH` variable?

**Comment by yrregnehc** [comment]
I downloaded Mingw64 and put it in the front of the path variable like this:

C:\Program Files\mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev0\mingw64\x86_64-w64-mingw32\bin;

I downloaded Dev-C++ though, and I'm not sure if it will affect the path.

**Comment by yrregnehc** [comment]
By the way, what's the easiest way to install gcc on windows?

**Comment by hzxie** [comment]
Please open `Command Prompt` and type:

```
gcc -v
```

What 's the output?

I install `gcc` with [MINGW](https://sourceforge.net/projects/mingw-w64/).

**Comment by yrregnehc** [comment]
I didn't do these two steps:
copy jawt_md.h  ..
copy jni_md.h  ..
what do they mean? Simply copy these two files to the parental directory?

**Comment by hzxie** [comment]
Yes.

**Comment by hzxie** [comment]
But I do think there's something wrong with your `gcc` and `PATH` variable.

**Comment by yrregnehc** [comment]
I think so, but I don't know how to install GCC effectively on Windows.

**Comment by hzxie** [comment]
So what's your output of `gcc -v`?

**Comment by yrregnehc** [comment]
![image](https://user-images.githubusercontent.com/29784649/27716292-64fd317a-5d0b-11e7-86a6-1af43e3e1bb8.png)

**Comment by hzxie** [comment]
Nice.

Please open `MINGW_HOME/bin`, where `MINGW_HOME` represents path where you install `gcc`.
Rename or copy `mingw32-make.exe` to `make.exe`.

**Comment by yrregnehc** [comment]
Okay, let me see

**Comment by yrregnehc** [comment]
It works now! Thanks so much!
