### ISSUE TITLE
web项目启动失败

### ISSUE THREAD

**Issue by chinghonsun** [hzxie/voj#28]
项目无法启动，tomcat报错：
[INFO] 2017-11-21 18:41:40,366 [localhost-startStop-1] com.alibaba.druid.pool.DruidDataSource - {dataSource-1} closed
21-Nov-2017 18:41:40.368 SEVERE [localhost-startStop-1] org.springframework.web.context.ContextLoader.initWebApplicationContext Context initialization failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/InvalidDefinitionException

**Comment by hzxie** [comment]
你Maven依赖没有下载全吧。

**Comment by chinghonsun** [comment]
com/fasterxml/jackson/databind/exc/InvalidDefinitionException 这个类是在哪个包的？

**Comment by hzxie** [comment]
It is obvious that the class is defined in the package named `com.fasterxml.jsckson`.
