### ISSUE TITLE
新的评测机为什么获取的运行内存信息为0

### ISSUE THREAD

**Issue by qchgood888** [hzxie/voj#30]
您好,很不错的一个项目,最近也一直在关注学习,但是您最近提交的这个提高效率的judger,我提交代码给评测机评测的时候为什么它跑的测试用例所获取的运行内存都为0.
currentUsedMemory: [PID #17698]0
[JNI DEBUG] usedTime: 4 ms
[JNI DEBUG] usedMemory: 0 KB
[JNI DEBUG] exitCode: 0

**Comment by qchgood888** [comment]
@hzxie 不好意思,问题不小心被我点错,关掉了 - - |,原本想配张图
![test06](https://user-images.githubusercontent.com/14218399/33659512-6a94615c-dabb-11e7-8bd0-6e29913d9828.png)

**Comment by hzxie** [comment]
因为程序运行时间太短了, 所以就没测到内存占用 - -|||

**Comment by qchgood888** [comment]
您的线上网站用的是最新的评测机吗

**Comment by hzxie** [comment]
不是。线上的那个是用`ptrace`实现的。
但是`ptrace`实在是太慢了。等我更新一下。

**Comment by qchgood888** [comment]
好像你线上的网站测评时所获取内存信息还是为0.

**Comment by hzxie** [comment]
因为程序运行时间太短了吧。
你提交一个TLE的程序估计可以测到内存了。

**Comment by qchgood888** [comment]
好像也是检测不到.
![i01 cf dpb5lm58qo j7vmp](https://user-images.githubusercontent.com/14218399/36017183-943f9df4-0db1-11e8-85a9-555723639bbf.png)

**Comment by hzxie** [comment]
Fixed.

**Comment by hzxie** [comment]
我也不知道为什么, 超奇怪的Bug.
换了一种实现.

**Comment by hzxie** [comment]
@qchgood888 
我看到你的新提交内存还是0 K, 我改了一下检测内存的时间间隔, 然后就可以检测到内存占用了.
一会儿我提交一下.
