### ISSUE TITLE
执行JNI返回512错误是什么原因？

### ISSUE THREAD

**Issue by chinghonsun** [hzxie/voj#31]
[JNI DEBUG] exitCode: 512

**Comment by hzxie** [comment]
那您要查一下操作系统的API, 返回512是什么意思.
您给的信息也忒少点了。操作系统也没写。
运行的代码也没写。

**Comment by chinghonsun** [comment]
我就是用A+B Problem这道试题，提交的代码如下：
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int a = in.nextInt();
        int b = in.nextInt();
        System.out.println(a + b);
    }
}

linux执行结果如下：

![image](https://user-images.githubusercontent.com/4075785/34045567-6b91984c-e1e4-11e7-85ff-37d0834661e9.png)

**Comment by hzxie** [comment]
那您需要检查一下Linux下进程返回512是什么意思。
您自己查一下吧。

**Comment by chinghonsun** [comment]
512错误就是No such file or directory
