### ISSUE TITLE
如何同时执行多个任务,给点建议？

### ISSUE THREAD

**Issue by chinghonsun** [hzxie/voj#32]
如何同时执行多个任务,给点建议？

**Comment by hzxie** [comment]
你多开几个judger就好啦……
judger可以跑在一台机器上，也可以跑在多台机器上。
建议跑在多台机器上。

**Comment by chinghonsun** [comment]
有没有办法可以做到，在同一台机器上跑多个judger？或者是，judger同时执行多个mq任务？

**Comment by hzxie** [comment]
可以呀。
Judger一次只可以执行一个MQ任务。
因为同时执行多个没有意义。
另外，一台机器上可以跑多个Judger的前提是计算机是多核处理器的。
否则会影响运行时间的测定。
