### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by casey23** [hzxie/voj#36]
大神你好，
      我在linux中跑的，judger端调用jni时报java.lang.UnsatisfiedLinkError这个错误，是不是.so要自己生成呢

**Comment by hzxie** [comment]
.so在`mvn package`命令时会自动生成.
抛出`java.lang.UnsatisfiedLinkError`是由于`mvn package`的时候`.so`没有成功构建.
具体的原因可能是`gcc`环境不满足条件或没有找到`jni.h`等文件.
请参见README.
