### ISSUE TITLE
关于编译动态依赖库的问题

### ISSUE THREAD

**Issue by EnjoyRenWei** [hzxie/voj#37]
复制的代码中的cpp文件和头文件，然后生成dll，一直报LNK2001:无法解析的外部符号CreateEnvironmentBlock
我用的是vs2013，请问author，您生成dll的时候遇到过这问题吗

**Comment by hzxie** [comment]
请仔细阅读README.
请使用GCC 4.8及以上版本编译。
谢谢。

**Comment by EnjoyRenWei** [comment]
好的谢谢，的确是我GCC版本太低

另外有个问题，调用本地方法的时候，标准输入文件（如1.in）每次只能指定一个？那要是多个检测点呢（如有1.in,2.in,3.in......），难道是要循环调用本地方法，然后指定不同的标准输入文件

**Comment by hzxie** [comment]
对 是的。
但是上层的Judger会自动循环调用。
而且底层的JNI实现只是用于运行程序并监测运行时内存及时间占用。
