### ISSUE TITLE
当采用多线程同时处理的时候,就会一直卡住不出任何结果,是什么原因呢?

### ISSUE THREAD

**Issue by chinghonsun** [hzxie/voj#39]
![image](https://user-images.githubusercontent.com/4075785/34970780-44ee8962-fab1-11e7-99c4-20180fcb08bf.png)

**Comment by hzxie** [comment]
多线程你怎么处理的?
我用了`synchronized`加锁, 所以多线程应该会被阻塞吧?

**Comment by chinghonsun** [comment]
synchronized处理效率太低了,我这边一下子过来就是几百个提交,必须改用多线程同时判题

**Comment by hzxie** [comment]
你可以多开几个进程啊
你用多线程时间测算会不准确吧
