### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Liberate99** [hzxie/voj#43]
target/classes下没有JudgerCore.dll这个文件

提交评测后voj报错：
 

 
     java.lang.UnsatisfiedLinkError:com.yunjuanyunshu.oj.judger.core.Runner.getRuntimeResult(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/util/Map;at com.yunjuanyunshu.oj.judger.core.Runner.getRuntimeResult(Native Method) ~[oj.judger.jar:?]
	    at com.yunjuanyunshu.oj.judger.core.Runner.getRuntimeResult(Runner.java:198) ~[oj.judger.jar:?]
	    at com.yunjuanyunshu.oj.judger.core.Compiler.getCompileResult(Compiler.java:75) ~[oj.judger.jar:?]
	    at com.yunjuanyunshu.oj.judger.core.Compiler.getCompileResult(Compiler.java:32) ~[oj.judger.jar:?]
	    at com.yunjuanyunshu.oj.judger.core.Dispatcher.compile(Dispatcher.java:126) ~[oj.judger.jar:?]
	    at com.yunjuanyunshu.oj.judger.core.Dispatcher.createNewTask(Dispatcher.java:66) ~[oj.judger.jar:?]
	    at com.yunjuanyunshu.oj.judger.application.ApplicationDispatcher.onSubmissionCreated(ApplicationDispatcher.java:35) ~[oj.judger.jar:?]
	    at com.yunjuanyunshu.oj.judger.messenger.MessageReceiver.newSubmissionHandler(MessageReceiver.java:53) ~[oj.judger.jar:?]
	    at com.yunjuanyunshu.oj.judger.messenger.MessageReceiver.onMessage(MessageReceiver.java:31) ~[oj.judger.jar:?]
	    at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:769) ~[oj.judger.jar:?]
	    at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:707) ~[oj.judger.jar:?]
	    at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[oj.judger.jar:?]
	    at org.springframework.jms.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:645) ~[oj.judger.jar:?]
	    at org.springframework.jms.listener.SimpleMessageListenerContainer.processMessage(SimpleMessageListenerContainer.java:322) ~[oj.judger.jar:?]
	    at org.springframework.jms.listener.SimpleMessageListenerContainer.lambda$createListenerConsumer$2(SimpleMessageListenerContainer.java:299) ~[oj.judger.jar:?]
	    at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1404) [oj.judger.jar:?]
	    at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [oj.judger.jar:?]
	    at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [oj.judger.jar:?]
	    at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [oj.judger.jar:?]
	    at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [oj.judger.jar:?]
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

 

$ mvn clean package -DskipTests                                              13:08:58 
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.yunjuanyunshu:oj.judger:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ line 292, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] --------------------< com.yunjuanyunshu:oj.judger >---------------------
[INFO] Building oj.judger 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (0 B at 0 B/s)
Downloading from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded from alimaven: http://maven.aliyun.com/nexus/content/groups/public/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar (0 B at 0 B/s)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ oj.judger ---
[INFO] Deleting /Users/apple/IdeaProjects/oj-judger/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ oj.judger ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ oj.judger ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 27 source files to /Users/apple/IdeaProjects/oj-judger/target/classes
[WARNING] /Users/apple/IdeaProjects/oj-judger/src/main/java/com/yunjuanyunshu/oj/judger/util/AES.java:[3,16] sun.misc.BASE64Encoder是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/apple/IdeaProjects/oj-judger/src/main/java/com/yunjuanyunshu/oj/judger/util/AES.java:[3,16] sun.misc.BASE64Encoder是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/apple/IdeaProjects/oj-judger/src/main/java/com/yunjuanyunshu/oj/judger/util/AES.java:[3,16] sun.misc.BASE64Encoder是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/apple/IdeaProjects/oj-judger/src/main/java/com/yunjuanyunshu/oj/judger/util/AES.java:[187,13] sun.misc.BASE64Encoder是内部专用 API, 可能会在未来发行版中删除
[WARNING] /Users/apple/IdeaProjects/oj-judger/src/main/java/com/yunjuanyunshu/oj/judger/util/AES.java:[187,37] sun.misc.BASE64Encoder是内部专用 API, 可能会在未来发行版中删除
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (default) @ oj.judger ---
[INFO] Executing tasks

jni:
     [echo] Generating JNI headers
     [exec] make: Nothing to be done for `all'.
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ oj.judger ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ oj.judger ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 10 source files to /Users/apple/IdeaProjects/oj-judger/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ oj.judger ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ oj.judger ---
[INFO] Building jar: /Users/apple/IdeaProjects/oj-judger/target/oj.judger.jar
[INFO] 
[INFO] --- maven-shade-plugin:3.0.0:shade (default) @ oj.judger ---
[INFO] Including org.springframework:spring-core:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-jcl:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-tx:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-beans:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-orm:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-jdbc:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-jms:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-context:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-aop:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-expression:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-messaging:jar:5.0.4.RELEASE in the shaded jar.
[INFO] Including org.aspectj:aspectjrt:jar:1.8.13 in the shaded jar.
[INFO] Including org.aspectj:aspectjtools:jar:1.8.13 in the shaded jar.
[INFO] Including org.mybatis:mybatis:jar:3.4.5 in the shaded jar.
[INFO] Including org.mybatis:mybatis-spring:jar:1.3.1 in the shaded jar.
[INFO] Including org.mybatis.caches:mybatis-ehcache:jar:1.1.0 in the shaded jar.
[INFO] Including net.sf.ehcache:ehcache-core:jar:2.6.11 in the shaded jar.
[INFO] Including com.alibaba:druid:jar:1.1.8 in the shaded jar.
[INFO] Including mysql:mysql-connector-java:jar:5.1.44 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.5 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-spring:jar:5.15.0 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.25 in the shaded jar.
[INFO] Including org.apache.xbean:xbean-spring:jar:4.2 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.0.3 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-broker:jar:5.15.0 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-client:jar:5.15.0 in the shaded jar.
[INFO] Including org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1 in the shaded jar.
[INFO] Including org.fusesource.hawtbuf:hawtbuf:jar:1.11 in the shaded jar.
[INFO] Including org.apache.geronimo.specs:geronimo-j2ee-management_1.1_spec:jar:1.0.1 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-openwire-legacy:jar:5.15.0 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:18.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.6.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.6.7 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-pool:jar:5.15.0 in the shaded jar.
[INFO] Including org.apache.activemq:activemq-jms-pool:jar:5.15.0 in the shaded jar.
[INFO] Including org.apache.geronimo.specs:geronimo-jta_1.0.1B_spec:jar:1.0.1 in the shaded jar.
[INFO] Including org.apache.commons:commons-pool2:jar:2.4.2 in the shaded jar.
[INFO] Including javax.jms:javax.jms-api:jar:2.0.1 in the shaded jar.
[INFO] Including org.apache.directory.studio:org.apache.commons.io:jar:2.4 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.4 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-core:jar:2.5 in the shaded jar.
[INFO] Including org.apache.logging.log4j:log4j-api:jar:2.5 in the shaded jar.
[WARNING] spring-jcl-5.0.4.RELEASE.jar, commons-logging-1.0.3.jar define 6 overlapping classes: 
[WARNING]   - org.apache.commons.logging.Log
[WARNING]   - org.apache.commons.logging.LogFactory$2
[WARNING]   - org.apache.commons.logging.impl.SimpleLog
[WARNING]   - org.apache.commons.logging.LogFactory$1
[WARNING]   - org.apache.commons.logging.impl.NoOpLog
[WARNING]   - org.apache.commons.logging.LogFactory
[WARNING] geronimo-jms_1.1_spec-1.1.1.jar, javax.jms-api-2.0.1.jar define 58 overlapping classes: 
[WARNING]   - javax.jms.QueueConnection
[WARNING]   - javax.jms.MessageNotReadableException
[WARNING]   - javax.jms.ObjectMessage
[WARNING]   - javax.jms.TopicRequestor
[WARNING]   - javax.jms.JMSException
[WARNING]   - javax.jms.InvalidSelectorException
[WARNING]   - javax.jms.Message
[WARNING]   - javax.jms.Topic
[WARNING]   - javax.jms.ServerSessionPool
[WARNING]   - javax.jms.JMSSecurityException
[WARNING]   - 48 more...
[WARNING] aspectjrt-1.8.13.jar, aspectjtools-1.8.13.jar define 130 overlapping classes: 
[WARNING]   - org.aspectj.internal.lang.reflect.SignaturePatternImpl
[WARNING]   - org.aspectj.runtime.reflect.SignatureImpl
[WARNING]   - org.aspectj.internal.lang.reflect.DeclareSoftImpl
[WARNING]   - org.aspectj.lang.reflect.AjType
[WARNING]   - org.aspectj.lang.annotation.control.CodeGenerationHint
[WARNING]   - org.aspectj.lang.JoinPoint$StaticPart
[WARNING]   - org.aspectj.runtime.internal.cflowstack.ThreadStackImpl11
[WARNING]   - org.aspectj.runtime.internal.cflowstack.ThreadStack
[WARNING]   - org.aspectj.internal.lang.reflect.InterTypeDeclarationImpl
[WARNING]   - org.aspectj.internal.lang.reflect.DeclareAnnotationImpl
[WARNING]   - 120 more...
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /Users/apple/IdeaProjects/oj-judger/target/oj.judger.jar with /Users/apple/IdeaProjects/oj-judger/target/oj.judger-1.0-SNAPSHOT-shaded.jar
[INFO] Dependency-reduced POM written at: /Users/apple/IdeaProjects/oj-judger/dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.113 s
[INFO] Finished at: 2018-09-14T13:10:08+08:00
[INFO] ------------------------------------------------------------------------

不知道怎么回事，求大神解答。

**Comment by hzxie** [comment]
macOS不能使用评测机。
因为没有实现相应的函数。

**Comment by Liberate99** [comment]
@hzxie 。。。好吧，谢谢。
