### ISSUE TITLE
CPU_TIME INSTEAD OF CLOCK_TIME?

### ISSUE THREAD

**Issue by YektaAnilAksoy** [hzxie/voj#44]
Hello @hzxie ,

If I am not wrong, you should have used **CPU_TIME** to measure spent time for the process, instead of using **CLOCK_TIME**.

**Comment by hzxie** [comment]
Maybe the CPU time is the same as clock time on a multi-core CPU?

**Comment by YektaAnilAksoy** [comment]
I have searched your argument on the internet. It seems you are right. Thank you for the new information :)
