### ISSUE TITLE
judge 问题

### ISSUE THREAD

**Issue by stonebian** [hzxie/voj#45]
我的环境都建立成功，配置也都设置了，但是提交代码时，总报编译错误，
[DEBUG] Memory file path = /proc/4121/statm
[DEBUG] fp == NULL in getCurrentUsedMemory(pid_t)
[DEBUG] Current Memory of PID# 4121: 0 KB
[DEBUG] usedTime: 5003 ms
[DEBUG] usedMemory: 0 KB
[DEBUG] exitCode: 9
我自己debug跟踪到C语言程序，这个我就不会跟踪了，不知道那个的问题，
我跟踪生成的临时文件，我手动编译没有问题。不知道那个问题。
感谢您的回复！

**Comment by haitaoya** [comment]
> 我的环境都建立成功，配置也都设置了，但是提交代码时，总报编错错误，
> [DEBUG]内存文件路径= / proc / 4121 / statm 
> [DEBUG] fp == getCurrentUsedMemory中的NULL（pid_t）
> [DEBUG] ] PID的当前存储器＃4121：0 KB 
> [DEBUG] usedTime：5003 ms 
> [DEBUG] usedMemory：0 KB 
> [DEBUG] exitCode：9 
> 我自己debug跟踪到C语言程序，这个我就不会跟踪了，不知道那个的问题，
> 我跟踪生成的临时文件，我手动编译没有问题。不知道那个问题。
> 感谢您的回复！

你好 我最近也在做oj，可以交流一下吗

**Comment by hzxie** [comment]
@stonebian 
Please provide more error logs.

**Comment by haitaoya** [comment]
@hzxie 
您好 请问 voj makefile 使用的 mingw 是哪个版本呢？ 我生成dll动态链接库时出现了问题

**Comment by hzxie** [comment]
@haitaoya 
Please give me more error logs.
I think the MINGW version above 4.8 is OK. **BUT** please make sure that you are using a 64 bit MINGW.

**Comment by haitaoya** [comment]
@hzxie 十分感谢您百忙之中解答我的问题。 
我使用的是win7 + eclipse + Mingw8.1.0（ 64 bit POSIX thread model ）
通过make生成dll链接库，运行ApplicationBootstrap后，无法调用dll，显示错误信息如下：
java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\JudgerCore5742222637989836704.dll: 找不到指定的程序。
[详细信息我写在了云笔记里](http://note.youdao.com/noteshare?id=9268f5a723a9b7a303fd0f9804100796)
加载不到dll，但是文件是存在的。
我之前使用win32 thread model，生成dll时将c++11线程相关代码注释掉，可以生成dll并且也可以调用。只是缺少了查询内存使用功能。
两种thread model生成的dll大小相差很大 POSIX 501kb，win32 148kb。
请问无法load到dll文件与thread model有关联吗？

十分感谢您的回复！

**Comment by haitaoya** [comment]
@hzxie 
您好，经过多次尝试，我分别使用 mingw-w64 8.1.0、6.3.0、5.4.0、4.8.1 都是 posix thread model ；只有 5.4.0 版本生成的 dll 可以识别，并且可以正常使用。（其他版本暂时还未测试）
请问mingw-w64 必须使用固定版本5.4.0才兼容吗？

**Comment by hzxie** [comment]
I don't think so. Because I tested it on **4.8.0** several years ago on Windows.
That's a strange problem.

**Comment by hzxie** [comment]
The error logs indicate that the generated `.dll` cannot be loaded into the application.
I think there's something wrong with `gcc`. But I don't know why other versions of `gcc` cannot work properly.

**Comment by hzxie** [comment]
Please refer to #42

**Comment by haitaoya** [comment]
@hzxie 
感谢您的回复！
或许是我的win7电脑系统和jdk问题，我找时间用其他系统电脑再进行一下测试。
使用docker部署是没有这个问题的。
如果遇到问题再向您请教，祝您工作愉快！

**Comment by hzxie** [comment]
@haitaoya 
Best wishes.

**Comment by kevinMintnick** [comment]
> @hzxie
> 您好，经过多次尝试，我分别使用mingw-w64 8.1.0、6.3.0、5.4.0、4.8.1都是posix线程模型；只有5.4.0版本生成的dll可以识别，并且可以正常使用。（其他版本暂时未测试）请问
> mingw-w64必须使用固定版本5.4.0才兼容吗？

您好，请问您解决注册dll这个问题了嘛？
我也是报错
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\JudgerCore5239036737798406355.dll: 找不到指定的程序。
环境：WindowsServer2019
Minggw-w64 5.4.0

**Comment by hzxie** [comment]
@kevinMintnick 
The build on [AppVeyor](https://ci.appveyor.com/project/hzxie/voj) indicates that everything goes well on Windows.
