### ISSUE TITLE
关于启动Judger的问题

### ISSUE THREAD

**Issue by EnjoyRenWei** [hzxie/voj#46]
现在我启动Judger运行代码的时候，在Windows下，报1058错误：无法启动服务。没有找到原因，请问作者有遇到过这种情况吗

**Comment by hzxie** [comment]
哪来的服务？Tomcat？

**Comment by EnjoyRenWei** [comment]
不是tomcat 我的是一个普通的Java程序，main方法里面加载执行。（包名那些是对的）

**Comment by EnjoyRenWei** [comment]
是在执行本地方法的时候，返回1058错误

**Comment by hzxie** [comment]
哪儿提示的1058？
请提供更多的日志。谢谢。

**Comment by EnjoyRenWei** [comment]
public static void main(String[] args) {
		// 1。加载dll
		try {
			System.loadLibrary("JudgerCore");
		} catch (Exception ex) {
			ex.printStackTrace();
			System.out.println(ex);
		}
		// 2。拼接编译命令
		String compileCommand = Compiler.getCompileCommandLine(
				"/resource/question/code/1/2/20190324183120580JAAM",
				"java");
		System.out.printf(compileCommand);
		// 3.调用本地方法进行编译
		Map<String, Object> compileResult = Compiler
				.getCompileResult(
						"javac F:/oj_files/resource/question/code/1/2/20190324183120580JAAM.java",
						"F:/oj_files/resource/question/code/1/3/20190326203308545XW54.log",
						100 * 1000, 512 * 1024);
	

> `}```


运行结果，Windows1058错误：服务无法启动，可能因为被禁用，也可能因为没有关联的可用设备：
Exception in thread "main" java.lang.Error: API:     CreateProcess
Code:    1058
Message: Î޷¨Æô¶¯·þÎñ£¬ԭÒò¿ÉÄÜÊÇÒѱ»½ûÓûòÓëÆäÏà¹Øjµ
	at com.cspm.judger.core.Runner.getRuntimeResult(Native Method)
	at com.cspm.judger.core.Runner.getCompileResult(Runner.java:118)
	at com.cspm.judger.core.Compiler.getCompileResult(Compiler.java:34)
	at com.cspm.judger.core.Runner.main(Runner.java:34)

**Comment by hzxie** [comment]
请检查Secondary Logon服务的属性是否为禁用（disabled）

**Comment by EnjoyRenWei** [comment]
啊啊啊啊啊，终于解决了，跪谢作者大大！！！折腾了好久啊，这是什么原因呢

**Comment by hzxie** [comment]
请参见Windows API。

**Comment by EnjoyRenWei** [comment]
索嘎，再次感谢作者
