### ISSUE TITLE
学习voj的过程中遇到的问题

### ISSUE THREAD

**Issue by haitaoya** [hzxie/voj#47]
您好，我在学习voj的过程中遇到一个问题
https://github.com/hzxie/voj/blob/5ccd8fe1a43314d9f1e305056d28b789b26e64e0/web/src/main/java/org/verwandlung/voj/web/messenger/ApplicationEventListener.java#L72 
这里为什么需要加synchronized (this) 进行同步呢，不加的话会引发什么问题吗？

（voj代码中竞赛模块的底层已经实现，怎么没开放竞赛功能呀？）

**Comment by hzxie** [comment]
@haitaoya 竞赛功能还有一些细节没有写完，而且写前端也需要时间呀。最近真的抽不出时间完善。
另外，`synchronized (this)`是为了防止一个消息被重复抓取。保证每个消息只被抓取一次。

**Comment by haitaoya** [comment]
@hzxie 很抱歉这么晚打扰您，感谢您的回复。
您说的防止重复抓取的消息是实时评测结果吗？但是synchronized (this)的同步代码块中只是定期清理离线评测机。 这个同步代码块是放在了ApplicationEventListener的构造函数中，应该只会执行一次吧。为什么需要使用synchronized 呢？

**Comment by hzxie** [comment]
抱歉，我看错了。更正一下。
这个是一个单例模式。整个类中只有一个scheduler。为了避免scheduler被重复构造，我们需要使用`synchronized`保证其唯一性。

**Comment by haitaoya** [comment]
@hzxie 嗯嗯，抱歉没能及时回复，我查询了一下相关资料，但是我还是有些不太清楚。当前`ApplicationEventListener`类注解  `@Component`  本身是单例模式吧，这个类构造方法只执行一次，还需要再使用 `synchronized` 构造单例模式吗？

**Comment by hzxie** [comment]
`@Component`本身是单例模式吗？有参考文献吗？
如果它本身是单例模式，那`synchronized`的确可以去除。

**Comment by haitaoya** [comment]
@hzxie 感谢解惑！（对java的高级应用不是了解，给您添麻烦了^_^）
