### ISSUE TITLE
日历显示不准确

### ISSUE THREAD

**Issue by haitaoya** [hzxie/voj#49]
![image](https://user-images.githubusercontent.com/43179881/56740934-79f66880-67a4-11e9-8c01-1787a96afdef.png)
https://github.com/hzxie/voj/blob/5ccd8fe1a43314d9f1e305056d28b789b26e64e0/web/src/main/java/org/verwandlung/voj/web/service/SubmissionService.java#L187
这里的startTime是2019/4/18的一个时间， 感觉应该后移一天吧，不然最后图表的显示最后会多出新的一列。

**Comment by hzxie** [comment]
没看懂 - -|||

**Comment by haitaoya** [comment]
尴尬...我描述的不太准确。
比如当前时间2019/4/26 9:20 ，按照查询本周7天提交记录.
这里
https://github.com/hzxie/voj/blob/5ccd8fe1a43314d9f1e305056d28b789b26e64e0/web/src/main/java/org/verwandlung/voj/web/service/SubmissionService.java#L174
生成的`Map<String, Long>` key 是从2019/4/20 到 2019/4/26 
但是下边的
https://github.com/hzxie/voj/blob/5ccd8fe1a43314d9f1e305056d28b789b26e64e0/web/src/main/java/org/verwandlung/voj/web/service/SubmissionService.java#L187
`startTimeString`就是当前时间2019/4/26 9:20 - 7天 也就是 2019/4/19 9:20 最后会查询出在2019/4/19 当天 9:20 之后提交的一组数据。 
https://github.com/hzxie/voj/blob/5ccd8fe1a43314d9f1e305056d28b789b26e64e0/web/src/main/java/org/verwandlung/voj/web/service/SubmissionService.java#L189
这里遍历的时候就会多出了2019/4/19的一个key
我觉得`startTimeString`应该后移一天去当天0点会比较准确吧。
我改成了这样：
![image](https://user-images.githubusercontent.com/43179881/56777628-2cf6ae80-6805-11e9-802d-e000b3c96082.png)

**Comment by hzxie** [comment]
哦，感谢指正。
如果可以的话，请提一个PR。

**Comment by haitaoya** [comment]
嗯嗯，好的。
VOJ的MarkDown编辑框是怎么实现的呀？
![image](https://user-images.githubusercontent.com/43179881/56782999-29baed00-681c-11e9-8ecd-c0bbf0c7a757.png)
哪里可以找到相关的学习 API 呢？

**Comment by hzxie** [comment]
这个使用了一个现有的库，在上面做了一些小修改。
请参见：https://verwandlung.org/assets/js/markdown.min.js
