### ISSUE TITLE
java代码编译错误

### ISSUE THREAD

**Issue by haitaoya** [hzxie/voj#50]
提交页面[voj提交页面详情](https://verwandlung.org/submission/1343)
题目
`P1000 A+B Problem`
代码
```
import java.util.Scanner;

public class Main {
	int add(int a,int b) {
		return a+b;
	}
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int a = in.nextInt();
        int b = in.nextInt();
        Main main=new Main();
        System.out.println(main.add(a, b));
    }
}
```
编译错误
```
Compile Error.

/tmp/voj-1343/NuWpqoaGFISb.java:11: error: cannot find symbol

    Main main=new Main();

    ^
symbol: class Main

location: class NuWpqoaGFISb

/tmp/voj-1343/NuWpqoaGFISb.java:11: error: cannot find symbol

    Main main=new Main();

                  ^
symbol: class Main

location: class NuWpqoaGFISb

2 errors

Compile Error, Time = 0 ms, Memory = 0 KB, Score = 0.
```

好像无法使用 `Main main=new Main();`

**Comment by haitaoya** [comment]
![image](https://user-images.githubusercontent.com/43179881/56879007-60e20600-6a89-11e9-975a-6efe9e6d117d.png)
是否是这里的原因呢

**Comment by haitaoya** [comment]
[voj 提交详情](https://verwandlung.org/submission/1349)
这里 直接提交 ` System.out.println();` 就AC了...

**Comment by hzxie** [comment]
是的。
编译的时候会更换类的名称。这是为了防止你们在程序里递归调用程序攻击评测机。

**Comment by haitaoya** [comment]
@hzxie  嗯，还有P1000 A+B Problem这道题目，直接提交`System.out.println();` 就能AC

**Comment by hzxie** [comment]
What？这？？？
晚些时候我检查一下评测机的代码吧。

**Comment by haitaoya** [comment]
嗯嗯，我大概找到了 问题位置。尝试修改一下....
![image](https://user-images.githubusercontent.com/43179881/56880964-64798b00-6a91-11e9-90dc-f5b5daa8044a.png)

**Comment by hzxie** [comment]
这个逻辑的确有问题。感谢指正。

**Comment by hzxie** [comment]
The problem has been solved.
See:
- https://verwandlung.org/submission/1349
- https://verwandlung.org/submission/1350
