### ISSUE TITLE
关于多个评测机的部署

### ISSUE THREAD

**Issue by haitaoya** [hzxie/voj#51]
可以在一台windows电脑上部署两个评测机吗？
我运行了`ApplicationBootstrap`两次，开启了 两个评测机，但是局域网中另两台电脑同时提交的话，只有一台提交的代码可以成功评测。 另一个在评测机报错`java.lang.Error: API:     SetupIoRedirection`

**Comment by haitaoya** [comment]
呃... 我知道原因了  两个评测机的`judger.workDir = F:/tmp
judger.checkpointDir = F:/tmp/eoj-testpoints`
路径冲突了...  不好意思- -

**Comment by hzxie** [comment]
机智！
请问你#50 解决了吗？

**Comment by haitaoya** [comment]
我认为，应该判断一下标准输出有没有遍历到最后
![image](https://user-images.githubusercontent.com/43179881/56936195-9ab61980-6b28-11e9-9610-c52182a10477.png)


[还有这里 i的起始坐标 应该是startIndex吧](https://github.com/hzxie/voj/blob/968187a87c3faf51e62ef9052382db1afe14d2b1/judger/src/main/java/org/verwandlung/voj/judger/core/Comparator.java#L146)

**Comment by hzxie** [comment]
我来改一波吧。你这样不对。因为没有忽略多余的空白字符。

**Comment by hzxie** [comment]
对。是的，应该是startIndex。
这个项目Open-source了这么多年，你是第一个发现这些错误的🤦‍♂️。

**Comment by haitaoya** [comment]
尴尬...  
因为想做一个OJ系统，您的VOJ系统写的规范，易懂。就仔细观摩一下源码，当做学习的过程。

**Comment by haitaoya** [comment]
[这里 返回的实时评测结果，应该加个判断吧](https://github.com/hzxie/voj/blob/968187a87c3faf51e62ef9052382db1afe14d2b1/judger/src/main/java/org/verwandlung/voj/judger/core/Dispatcher.java#L171)
```
if("AC".equals(runtimeResult.get("runtimeResult"))) {
				runtimeResult.put("score", checkpointScore);
			}
			else {
				runtimeResult.put("score", 0);
			}
```

**Comment by hzxie** [comment]
不AC不一定是0分啊。

**Comment by haitaoya** [comment]
但是后边的操作都是按AC判断的
[持久化](https://github.com/hzxie/voj/blob/044e69f2076a68abac8ee8869cdafa52a2dfa820/judger/src/main/java/org/verwandlung/voj/judger/application/ApplicationDispatcher.java#L160)
[格式化log](https://github.com/hzxie/voj/blob/044e69f2076a68abac8ee8869cdafa52a2dfa820/judger/src/main/java/org/verwandlung/voj/judger/application/ApplicationDispatcher.java#L292)

**Comment by hzxie** [comment]
后面的2处应该是对每个checkpoint的判断。
你刚才说的那处是对整个Problem中Checkpoints的判断。

**Comment by haitaoya** [comment]
https://github.com/hzxie/voj/blob/968187a87c3faf51e62ef9052382db1afe14d2b1/judger/src/main/java/org/verwandlung/voj/judger/core/Dispatcher.java#L171
不是呀，这个也是对每个checkpoint的局部成绩计算（在for循环里边，返回的是单个checkpoint评测结果）

**Comment by haitaoya** [comment]
![image](https://user-images.githubusercontent.com/43179881/56938518-11591400-6b35-11e9-8779-35191c3af1d9.png)
![image](https://user-images.githubusercontent.com/43179881/56938524-19b14f00-6b35-11e9-9922-5b4435cf8003.png)
为什么时间超过了限制，exitCode却是0。   是因为超出的比较少吗  - -#

**Comment by hzxie** [comment]
应该是发现超时之后会触发KILL机制。
但是KILL的时候进程已经正常退出了。所以exit code是0。
