### ISSUE TITLE
为什么页面没有样式

### ISSUE THREAD

**Issue by 904407541** [hzxie/voj#53]
![40ZF @7L@EXJRD3}8BY2DDM](https://user-images.githubusercontent.com/44925296/57281842-5e615b00-70de-11e9-8591-3fe44d24ebef.png)
页面没有样式

**Comment by hzxie** [comment]
Please check the configuration in the `voj.properties` located in `web/src/main/resources`.
Thanks.

**Comment by kerorojason** [comment]
我也遇到同樣問題，想請問樓主如何解決的？謝謝

**Comment by hzxie** [comment]
@kerorojason 
Please check the configuration in the `voj.properties` located in `web/src/main/resources`.

**Comment by kerorojason** [comment]
I didn't change any configuration, and it worked all right at first.
Should I change any configuration?
Thank you!

**Comment by hzxie** [comment]
Please provide more error logs. (Open the Web Developer Tools, and find out the specific reason of 404/403)

**Comment by kerorojason** [comment]
The request fails with pending status.

**Comment by kerorojason** [comment]
The request keep pending and cannot get response

**Comment by hzxie** [comment]
@kerorojason 
Obviously, you deployed the website to 140.112.183.212:25.. 
However, static resources are requested from localhost:8080. It seems that the URL for static resources are not correct.

As mentioned above, please check the configuration in the `voj.properties` located in `web/src/main/resources`.

**Comment by kerorojason** [comment]
Fixed it.
I edited the config in /opt/tomcat/webapps/voj/WEB-INF/classed/voj.properties
Thanks for your help.
Btw, could you remove the ip address you mentioned in your comment? Thx!

**Comment by 904407541** [comment]
I changed bro




------------------ 原始邮件 ------------------
发件人: "Jason Wang"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 中午11:40
收件人: "hzxie/voj"<voj@noreply.github.com>; 
抄送: "沈晨杰"<904407541@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [hzxie/voj] 为什么页面没有样式 (#53)




Fixed it.
 I edited the config in /opt/tomcat/webapps/voj/WEB-INF/classed/voj.properties
 Thanks for your help.
 Btw, could you remove the ip address you mentioned in your comment? Thx!
 
&mdash;
