### ISSUE TITLE
有没有现存的测试数据与题目？

### ISSUE THREAD

**Issue by ewitt11** [hzxie/voj#56]
感觉测试数据和题目自己一条一条加太麻烦了，有没有现存的可以导入的数据库？
谁有的发下我的邮箱:       ewitt11@163.com

**Comment by hzxie** [comment]
The same issue as #11 
我计划开发一个导入工具，然而一直都没有抽出时间。

**Comment by zhblue** [comment]
tk.hustoj.com
以及
https://github.com/zhblue/freeproblemset/tree/master/fps-examples
