### ISSUE TITLE
Docker部署後提交評測內存使用量過大

### ISSUE THREAD

**Issue by kerorojason** [hzxie/voj#58]
我使用docker在我的mac本機運行，
在測試提交 **P1000 A+B Problem** 這個試題的Java解時，
程式運行的內存使用量都會超過30000KB，
示意圖：
![image](https://user-images.githubusercontent.com/15242893/63632646-40a80980-c66d-11e9-9885-8737cfff7dc6.png)

我嘗試提交C++ 程式碼得到結果為時間：207 ms，內存：1876 K，
所以硬體影響應該不致於差那麼多？
謝謝作者！

**Comment by zhblue** [comment]
这跟内存的计算方式有关，jvm启动时会狮子大开口，声称要很多内存，但是要走了以后并不真的用光，Linux有CoW机制，只有真正写入了的内存才会产生缺页中断，因此用缺页计数来计算的内存是实际消耗的内存。
这里是源码，显示voj用的是proc文件系统中的VmRSS，即驻留内存大小。
Mac本机显示的是对应VmSize。
因此存在差异实属正常。
https://github.com/hzxie/voj/blob/master/judger/src/main/cpp/unix/Judger.Core.Runner.cpp#L328

  /proc/[pid]/statm
              Provides information about memory usage, measured in pages.  The
              columns are:

                  size       (1) total program size
                             (same as VmSize in /proc/[pid]/status)
                  resident   (2) resident set size
                             (same as VmRSS in /proc/[pid]/status)
                  share      (3) shared pages (i.e., backed by a file)
                  text       (4) text (code)
                  lib        (5) library (unused in Linux 2.6)
                  data       (6) data + stack
                  dt         (7) dirty pages (unused in Linux 2.6)

**Comment by hzxie** [comment]
@zhblue 
感谢您的耐心解答。
所以您的意思是读取statm是不准确的？应该去读取缺页计数对吧？

**Comment by zhblue** [comment]
statm大致上上就是缺页，我猜测如此。

**Comment by zhblue** [comment]
VmRSS会松一些，VmSize会严一些，我倾向于对虚拟机语言松一些，对native的（c/cpp/pascal）严一些。

**Comment by kerorojason** [comment]
感謝回答！

**Comment by kerorojason** [comment]
長知識了~謝謝兩位，
但是小弟能力不足，
可能要勞駕兩位修改了!
