### ISSUE TITLE
非8080端口映射docker安装，远程访问，资源文件有问题

### ISSUE THREAD

**Issue by weifding** [hzxie/voj#59]
启动方式
docker run -d --name voj.web -p 6080:8080 zjhzxhz/voj.web
非本机访问 http://xxx.xx.xx.xx:6080/voj/
页面打开之后，css样式丢失。查看源代码
css和js地址还是http://localhost:8080/地址

<meta charset="UTF-8">
--
  | <title>首页 \| Verwandlung Online Judge</title>
  | <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <meta name="description" content="Verwandlung Online Judge is a cross-platform online judge system based on Spring MVC Framework.">
  | <meta name="author" content="Haozhe Xie">
  | 
  | <link href="http://localhost:8080/voj/assets/img/favicon.ico?v=226111d" rel="shortcut icon" type="image/x-icon">
  | 
  | <link rel="stylesheet" type="text/css" href="http://localhost:8080/voj/assets/css/bootstrap.min.css?v=226111d" />
  | <link rel="stylesheet" type="text/css" href="http://localhost:8080/voj/assets/css/bootstrap-responsive.min.css?v=226111d" />
  | <link rel="stylesheet" type="text/css" href="http://localhost:8080/voj/assets/css/flat-ui.min.css?v=226111d" />
  | <link rel="stylesheet" type="text/css" href="http://localhost:8080/voj/assets/css/font-awesome.min.css?v=226111d" />
  | <link rel="stylesheet" type="text/css" href="http://localhost:8080/voj/assets/css/style.css?v=226111d" />
  | <link rel="stylesheet" type="text/css" href="http://localhost:8080/voj/assets/css/misc/homepage.css?v=226111d" />
  | 
  | <script type="text/javascript" src="http://localhost:8080/voj/assets/js/jquery-1.11.1.min.js?v=226111d"></script>
  | <script type="text/javascript" src="http://localhost:8080/voj/assets/js/bootstrap.min.js?v=226111d"></script>
  | <script type="text/javascript" src="http://localhost:8080/voj/assets/js/md5.min.js?v=226111d"></script>
  | 
  | 
  | 
  | </head>
  | <body>

**Comment by Pipepw** [comment]
请问你的问题是怎么解决的呢

**Comment by KumiXH** [comment]
修改WEB项目配置文件中的CDN地址为你的IP地址即可
