### ISSUE TITLE
admin login into the system

### ISSUE THREAD

**Issue by csronnie** [hzxie/voj#60]
After successfully deploying the system using Docker, I can get into the initial login screen. However, I cannot find any information on the user name and password to login in to the system as administrator. What is the user name and password to login to create problem sets (or performing administration)

**Comment by hzxie** [comment]
Both the username and password are `zjhzxhz`.

**Comment by mtx2d** [comment]
> Both the username and password are `zjhzxhz`.

Thanks, this was really hard to find in the code!

**Comment by hzxie** [comment]
@mtx2d 
It is not in the code but in the database.
