### ISSUE TITLE
Docker 部署后 访问静态资源基于地址是 localhost

### ISSUE THREAD

**Issue by ShenQingchuan** [hzxie/voj#63]
如题，我按照您的教程部署之后，能在 /voj 页面下看到了 但是...
访问发现页面没有样式
一看发现请求去的地址是 localhost ...

这一点 对用docker部署的 怎么解决呀？ 是需要在启动时 填写什么配置吗？
对您的项目十分感激！
已Star

**Comment by ShenQingchuan** [comment]
好吧 我的错😂 应该先看看以往的 issues... 已经找到了问题所在

**Comment by Pipepw** [comment]
我也遇到了这个问题，请问你的问题是怎么解决的呢，我在之前的issues没看到相关的问题
