### ISSUE TITLE
关于judger打包和启动的问题

### ISSUE THREAD

**Issue by Crystal-FizZ** [hzxie/voj#64]
您好，我现在这边遇到问题，judge这部分进行打包的时候，makefile一直无法创建JudgerCore.dll，导致后面judge这部分启动不来，可以帮忙看一下吗

**Comment by Crystal-FizZ** [comment]
![image](https://user-images.githubusercontent.com/41418551/69519139-34955600-0f94-11ea-8b19-d88c68b30179.png)

**Comment by Crystal-FizZ** [comment]
![image](https://user-images.githubusercontent.com/41418551/69519397-e7fe4a80-0f94-11ea-9bdb-0f75a9643ade.png)

**Comment by hzxie** [comment]
你在judger目录下执行make输出什么？

**Comment by Crystal-FizZ** [comment]
> 你在judger目录下执行make输出什么？

我执行以下，稍等

**Comment by Crystal-FizZ** [comment]
> > 你在judger目录下执行make输出什么？
> 
> 我执行以下，稍等

![image](https://user-images.githubusercontent.com/41418551/69522655-f05a8380-0f9c-11ea-83e4-b955a810d96f.png)

**Comment by Crystal-FizZ** [comment]
> 你在judger目录下执行make输出什么？

方便加个微信交流下吗？

**Comment by hzxie** [comment]
你在judger目录下执行make输出什么？

**Comment by hzxie** [comment]
把mkdir -p删掉
手动创建目录target/classes

**Comment by Crystal-FizZ** [comment]
> 把mkdir -p删掉
> 手动创建目录target/classes

![image](https://user-images.githubusercontent.com/41418551/69523389-bee2b780-0f9e-11ea-83c1-488ee83c7cca.png)

**Comment by hzxie** [comment]
include下有一个文件夹 里面应该有jni.h，把它复制到include下。

**Comment by Crystal-FizZ** [comment]
![image](https://user-images.githubusercontent.com/41418551/69592845-3d3c6980-1032-11ea-85fc-211b5c4c58b5.png)
复制过去了，然后执行make命令

**Comment by Crystal-FizZ** [comment]
结果这样，帮忙看看
![image](https://user-images.githubusercontent.com/41418551/69592888-5b09ce80-1032-11ea-9285-74c76c14ffe4.png)

**Comment by hzxie** [comment]
看起来是Windows API有调整？
另外，你的MINGW是32位的 你需要安装64位的。

**Comment by hzxie** [comment]
Closed due to the inactivity.
