### ISSUE TITLE
丢失前端样式

### ISSUE THREAD

**Issue by kevinMintnick** [hzxie/voj#68]
Failed to load resource: the server responded with a status of 404 ()
bootstrap-responsive.min.css:1 Failed to load resource: the server responded with a status of 404 ()
flat-ui.min.css:1 Failed to load resource: the server responded with a status of 404 ()
font-awesome.min.css:1 Failed to load resource: the server responded with a status of 404 ()
style.css:1 Failed to load resource: the server responded with a status of 404 ()
homepage.css:1 Failed to load resource: the server responded with a status of 404 ()
bootstrap.min.js:1 Failed to load resource: the server responded with a status of 404 ()
md5.min.js:1 Failed to load resource: the server responded with a status of 404 ()
jquery-1.11.1.min.js:1 Failed to load resource: the server responded with a status of 404 ()
logo.png:1 Failed to load resource: the server responded with a status of 404 ()
avatar.jpg:1 Failed to load resource: the server responded with a status of 404 ()
bootstrap.min.js:1 Failed to load resource: the server responded with a

**Comment by hzxie** [comment]
Please double-check the value of `url.cdn` in `voj.properties`.

https://github.com/hzxie/voj/blob/master/web/src/main/resources/voj.properties#L31

**Comment by hzxie** [comment]
Please double-check the value of `url.cdn` in `voj.properties`.

https://github.com/hzxie/voj/blob/master/web/src/main/resources/voj.properties#L31
