### ISSUE TITLE
Flag Not Updated for the Last Problem After AC

### ISSUE THREAD

**Issue by kevinMintnick** [hzxie/voj#70]
是什么问题呢？

**Comment by kevinMintnick** [comment]
好像是最后一个题目AC后会不更新标志

**Comment by hzxie** [comment]
抱歉 无法复现。
您至少得说一下操作的过程吧。

**Comment by kevinMintnick** [comment]
在后台添加两个试题 P1004和P1005
然后各自给这两个试题提交正确代码 AC后 P1005试题无法显示FLAG标志

**Comment by kevinMintnick** [comment]
在您的DEMO网站也存在这个问题
请查看这两个图片：
https://imgchr.com/i/1o5HYR
https://imgchr.com/i/1o57k9

**Comment by kevinMintnick** [comment]
https://imgchr.com/i/1oIZnS 这张图片提交数从30提高到31 AC率从13提高到16 但FLAG依旧没有更新

**Comment by hzxie** [comment]
Fixed.
