### ISSUE TITLE
UnsatisfiedLinkError: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by kevinMintnick** [hzxie/voj#71]
环境：Java JDK1.8
系统：Windows10 X64

**Comment by hzxie** [comment]
Please provide more information such as logs.
Is your JDK 64 bit?
What's your version of GCC? Please provide the output of `g++ -v`.

**Comment by kevinMintnick** [comment]
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=C:/mingw32/bin/../libexec/gcc/i686-w64-mingw32/4.8.2/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../../../src/gcc-4.8.2/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw482/i686-482-posix-sjlj-rt_v3-rev4/mingw32 --with-gxx-include-dir=/mingw32/i686-w64-mingw32/include/c++ --enable-shared --enable-static --enable-targets=all --enable-multilib --enable-languages=ada,c,c++,fortran,objc,obj-c++,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-sjlj-exceptions --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch-32=i686 --with-arch-64=nocona --with-tune-32=generic --with-tune-64=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw482/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw482/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw482/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw482/prerequisites/i686-w64-mingw32-static --with-cloog=/c/mingw482/prerequisites/i686-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='i686-posix-sjlj-rev4, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw482/i686-482-posix-sjlj-rt_v3-rev4/mingw32/opt/include -I/c/mingw482/prerequisites/i686-zlib-static/include -I/c/mingw482/prerequisites/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw482/i686-482-posix-sjlj-rt_v3-rev4/mingw32/opt/include -I/c/mingw482/prerequisites/i686-zlib-static/include -I/c/mingw482/prerequisites/i686-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw482/i686-482-posix-sjlj-rt_v3-rev4/mingw32/opt/lib -L/c/mingw482/prerequisites/i686-zlib-static/lib -L/c/mingw482/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware'
Thread model: posix
gcc version 4.8.2 (i686-posix-sjlj-rev4, Built by MinGW-W64 project)

**Comment by hzxie** [comment]
i686 -> 32 bit
Please use 64 bit GCC.

**Comment by kevinMintnick** [comment]
非常感谢，
我尝试替换为x64的gcc之后，运行法官提示
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\i\AppData\Local\Temp\JudgerCore14116794251533357534.dll: Can't find dependent libraries
这应该是找不到依赖库的错误，但是在这个目录下的确有这个dll文件。

=====
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/5.4.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.4.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/c/mingw540/x86_64-540-posix-seh-rt_v5-rev0/mingw64 --with-gxx-include-dir=/mingw64/x86_64-w64-mingw32/include/c++ --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-isl-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/c/mingw540/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/c/mingw540/prerequisites/x86_64-w64-mingw32-static --with-mpc=/c/mingw540/prerequisites/x86_64-w64-mingw32-static --with-isl=/c/mingw540/prerequisites/x86_64-w64-mingw32-static --with-pkgversion='x86_64-posix-seh-rev0, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/c/mingw540/x86_64-540-posix-seh-rt_v5-rev0/mingw64/opt/include -I/c/mingw540/prerequisites/x86_64-zlib-static/include -I/c/mingw540/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/c/mingw540/x86_64-540-posix-seh-rt_v5-rev0/mingw64/opt/include -I/c/mingw540/prerequisites/x86_64-zlib-static/include -I/c/mingw540/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/c/mingw540/x86_64-540-posix-seh-rt_v5-rev0/mingw64/opt/lib -L/c/mingw540/prerequisites/x86_64-zlib-static/lib -L/c/mingw540/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 5.4.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

**Comment by hzxie** [comment]
Please refer to #42.
