### ISSUE TITLE
judge运行报空指针

### ISSUE THREAD

**Issue by doublexiaofeng** [hzxie/voj#78]
有个小问题想请教一下，我是直接在idea运行该项目，当调用native方法---
public native Map<String, Object> getRuntimeResult(String commandLine,String systemUsername, String systemPassword, String inputFilePath,String outputFilePath, int timeLimit, int memoryLimit);
时会报空指针错误，这是什么原因呢，万分感谢

**Comment by hzxie** [comment]
你构建C++了吗？翻一下历史的issue，你应该可以找到答案。

**Comment by doublexiaofeng** [comment]
你好，我已经复制了这两个文件了

![image](https://user-images.githubusercontent.com/40269842/86528309-5e730b80-bed9-11ea-80d6-c31309eea213.png)
这样是否就算是构建c++？我在其他问题没有找到这个解决办法，很抱歉打扰您。
似乎运行测试方法还是会报空指针错误
![image](https://user-images.githubusercontent.com/40269842/86528339-9e39f300-bed9-11ea-9224-3e064ffd9026.png)

**Comment by hzxie** [comment]
烦请您好好看一下README。如何构建C++的库写的很清楚了。
感谢！

**Comment by doublexiaofeng** [comment]
你好，我是按照readme步骤执行的，但是还是会出现以下问题
![image](https://user-images.githubusercontent.com/40269842/86529327-671c0f80-bee2-11ea-9fe7-bae8de2882d3.png)
将mkdir -p删除之后变成这样
![image](https://user-images.githubusercontent.com/40269842/86529348-9fbbe900-bee2-11ea-9db3-e7b16139992e.png)
maven，gcc，make路径都已经设置好了的

**Comment by hzxie** [comment]
Refer to #72

**Comment by doublexiaofeng** [comment]
不好意思，我在#72并未能找到适合自己的解决办法，我不是很清楚自己是在哪个部分出错导致空指针异常，您能解释一下吗？万分感谢！

**Comment by hzxie** [comment]
你手动执行一下：
```
mkdir target\cpp
make
```
可以解决吗？

**Comment by doublexiaofeng** [comment]
执行mkdir target\cpp之后再执行make结果如下
![image](https://user-images.githubusercontent.com/40269842/86531707-20d0ab80-bef6-11ea-819b-034de1ff8c9e.png)

**Comment by hzxie** [comment]
你这错误信息都不给全。根据你给的信息我无法给出建议。
另外，现在的代码是可以通过[AppVeyor](https://ci.appveyor.com/project/hzxie/voj)的持续集成测试的，请知悉。

**Comment by doublexiaofeng** [comment]
![image](https://user-images.githubusercontent.com/40269842/86532904-dce2a400-beff-11ea-885a-dd86f3b378df.png)
不好意思

**Comment by hzxie** [comment]
Please refer to https://github.com/libusb/libusb/issues/21
