### ISSUE TITLE
用docker搭建之后，js资源不能加载

### ISSUE THREAD

**Issue by Pipepw** [hzxie/voj#81]
![image-20200803122001249](https://raw.githubusercontent.com/Pipepw/FigureBed/master/blog_files/img/PicGo-Github-PicBed/image-20200803122001249.png)

**Comment by hzxie** [comment]
Docker的配置文件写的是localhost。如果你部署在非localhost可访问的服务器上，请先修改配置文件。

**Comment by Pipepw** [comment]
好的，我解决了，之前一直改错了地方，原来要改tomcat目录下的配置文件，谢谢
