### ISSUE TITLE
OI竞赛不能进入试题详情页面

### ISSUE THREAD

**Issue by Pipepw** [hzxie/voj#84]
![图片](https://user-images.githubusercontent.com/41220023/89729659-5c691300-da6a-11ea-91e1-e7c6971d9cb2.png)

ContestService.java的getCodeSnippetOfContestProblem方法中，codeSnippet初始值为null，所以会引发空指针异常，OI竞赛不能进入试题详情页面

**Comment by hzxie** [comment]
Cannot reproduce your error. Please give a more detailed description to help me to reproduce it.

**Comment by Pipepw** [comment]
在您发布的版本中，没有live状态的OI制竞赛，我在完善竞赛功能时，添加OI制的竞赛之后，点击试题不能进入详情页面，会出现空指针错误
您将样例第二个竞赛，也就是live状态的竞赛修改为OI制之后，就可以复现这个问题
![图片](https://user-images.githubusercontent.com/41220023/89747838-14da9980-daf3-11ea-81df-5c4fede090a3.png)

点击竞赛中的试题就会出现这个错误，因为是在服务器端，所以可能看起来不够明了

**Comment by hzxie** [comment]
Got it.
Would you mind to create a PR to solve this bug? Thank you very much.

**Comment by Pipepw** [comment]
第一次PR，好像有点不对劲

**Comment by hzxie** [comment]
Fixed in #88
