### ISSUE TITLE
您好，Software-Architecture不能访问

### ISSUE THREAD

**Issue by Pipepw** [hzxie/voj#89]
您好，我用火狐和Chrome都不能访问Software-Architecture，修改hosts之后同样如此
![图片](https://user-images.githubusercontent.com/41220023/90087174-aeea4e00-dd4e-11ea-882e-2d671cf1a7c3.png)
![图片](https://user-images.githubusercontent.com/41220023/90087192-bad61000-dd4e-11ea-9fbd-67497bd47d4a.png)
请问有没有其他地方可以看到Software-Architecture呢，我想将评测机放到不同的服务器上，但是不知道该怎么做，感谢！

**Comment by hzxie** [comment]
Please check your Internet connection.

**Comment by hzxie** [comment]
You can simply run judger on another server.
