### ISSUE TITLE
Docker安装出问题

### ISSUE THREAD

**Issue by LiuTianyouOnLuogu** [hzxie/voj#90]
我在Docker Run之后，8080端口直接出现Tomcat的界面，什么也没有，咋办

**Comment by LiuTianyouOnLuogu** [comment]
If you're seeing this, you've successfully installed Tomcat. Congratulations!

**Comment by LiuTianyouOnLuogu** [comment]
等等，似乎可以访问localhost:8080/voj

**Comment by LiuTianyouOnLuogu** [comment]
但是格式不对

**Comment by LiuTianyouOnLuogu** [comment]
```

Contest #3ACM开始时间: 2038年1月18日 上午12:00:00结束时间: 2038年1月18日 上午2:00:00 | Ready
-- | --
Contest #2ACM开始时间: 1970年1月2日 上午12:00:01结束时间: 2038年1月18日 上午3:14:07 | Live
Contest #1OI开始时间: 2018年2月23日 上午12:00:00结束时间: 2018年2月23日 下午11:59:59 | Done


```

**Comment by LiuTianyouOnLuogu** [comment]
![捕获](https://user-images.githubusercontent.com/61583168/91047570-dee9f900-e64c-11ea-986b-c58d3d7411c8.PNG)

**Comment by hzxie** [comment]
Refer to #81

**Comment by hzxie** [comment]
See also #68

**Comment by LiuTianyouOnLuogu** [comment]
@hzxie 抱歉我不会搞tomcat，请问我是不是应该改Dockerfile

**Comment by LiuTianyouOnLuogu** [comment]
是否应该设为0.0.0.0

**Comment by LiuTianyouOnLuogu** [comment]
我其实直接127.0.0.1:8080 -> 0.0.0.0:8080做个端口转发就行了

**Comment by LiuTianyouOnLuogu** [comment]
@hzxie sorry.
SCRIPT5009: SCRIPT5009: '$' is not defined 重复了5次
然后没了。没有localhost的错误

**Comment by LiuTianyouOnLuogu** [comment]
我已经做端口转发了，为啥还是不行

**Comment by LiuTianyouOnLuogu** [comment]
我应该如何修改配置

**Comment by LiuTianyouOnLuogu** [comment]
麻烦大神……我不会……

**Comment by LiuTianyouOnLuogu** [comment]
现在Docker镜像正在运行，我不想打扰Docker，所以如何在外部处理？还是根本不可能？
我不太明白咋整

**Comment by LiuTianyouOnLuogu** [comment]
算了，弃坑
