### ISSUE TITLE
idea mvn compile报错,求解决

### ISSUE THREAD

**Issue by hzh0425** [hzxie/voj#94]
idea中运行mvn compile(按照教程) ,报错如下(就是makefile的语法错误),MakeFile文件未改动,该怎么办?
mvn compile如下:
![image](https://user-images.githubusercontent.com/58988019/97298700-cab1ba80-188e-11eb-8338-14aa7a87e37f.png)
run makefile如下:
![image](https://user-images.githubusercontent.com/58988019/97298658-b79eea80-188e-11eb-81cc-fa4113b0412a.png)

**Comment by hzxie** [comment]
Please refer to README and stop asking stupid questions.
Thank you.

**Comment by hzh0425** [comment]
> 请参阅自述文件，然后停止提出愚蠢的问题。
> 谢谢。

我就是按照readme流程来的啊,就是报错

**Comment by hzh0425** [comment]
> The errors said very clear that "系统找不到指定的文件".
> So what is the reason causing the problem?

你好,如果你是指reademe中提到的两个头文件的话,确实已经复制到了${JAVA_HOME}/include 目录下
![image](https://user-images.githubusercontent.com/58988019/97305932-b5418e00-1898-11eb-96d6-9302b30bc730.png)
另外,上面的报错并没有提示是哪个文件找不到?
敬请赐教

**Comment by hulibabaii** [comment]
![image](https://user-images.githubusercontent.com/5887115/97554795-3f613200-1a12-11eb-96f6-c7b05524666d.png)
我也出现类似问题，但是有提示makefile执行有误

**Comment by hzxie** [comment]
@hulibabaii 
Refer to #95.
但凡你翻一下issues都不用再这里被动地等待回复。

**Comment by hzxie** [comment]
@hulibabaii @hzh0425 
另外，请二位明白我们的代码通过了在Windows上的CI构建。请不要随便怀疑脚本/代码有问题。
Refer to https://ci.appveyor.com/project/hzxie/voj
