### ISSUE TITLE
compile报错

### ISSUE THREAD

**Issue by hzh0425** [hzxie/voj#95]
执行完:
![image](https://user-images.githubusercontent.com/58988019/97307600-ddca8780-189a-11eb-894e-6a45087d98bc.png)
报错:
![image](https://user-images.githubusercontent.com/58988019/97307624-e3c06880-189a-11eb-9ce2-439ce18501b2.png)

**Comment by hzxie** [comment]
Please install MINGW or change:

```
mkdir -p target/cpp
```
to

```
mkdir -p target\cpp
```

**Comment by hzxie** [comment]
Please **STOP** creating new issues!!
Thank you.

**Comment by hzh0425** [comment]
ok fine!
再次遇到bug,jawt.h:
![image](https://user-images.githubusercontent.com/58988019/97318177-8cc09080-18a6-11eb-80d6-6e9cd28aae8c.png)
请问该如何解决

**Comment by hzh0425** [comment]
> Please **STOP** creating new issues!!
> Thank you.

ok fine!
再次遇到bug,jni.h已经在同目录下了
jawt.h:
![image](https://user-images.githubusercontent.com/58988019/97318306-af52a980-18a6-11eb-971f-e1e2fd6b4825.png)
