### ISSUE TITLE
界面显示问题

### ISSUE THREAD

**Issue by regotto-xqk** [hzxie/voj#99]
我按照你的方式, 启动对应 docker 镜像, 查看镜像日志, 应用程序都启动成功, 但是访问对应的界面出现的问题是界面 js, css显示失效.
![image](https://user-images.githubusercontent.com/38233189/103528116-60387e80-4ebe-11eb-91fd-21a26e297800.png)

**Comment by hzxie** [comment]
所以你CSS/JS请求的地址是什么？

**Comment by hzxie** [comment]
配置文件里CDN的地址改了吗？

**Comment by regotto-xqk** [comment]
cdn没改,&nbsp;尴尬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haozhe Xie"<notifications@github.com&gt;; 
发送时间: 2021年1月4日(星期一) 晚上8:25
收件人: "hzxie/voj"<voj@noreply.github.com&gt;; 
抄送: "2393536597"<2393536597@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hzxie/voj] 界面显示问题 (#99)





 
配置文件里CDN的地址改了吗？

**Comment by regotto-xqk** [comment]
哥,&nbsp;那个cdn是咋配置的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hzxie/voj"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月4日(星期一) 晚上8:25
收件人:&nbsp;"hzxie/voj"<voj@noreply.github.com&gt;;
抄送:&nbsp;"2393536597"<2393536597@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hzxie/voj] 界面显示问题 (#99)





 
配置文件里CDN的地址改了吗？

**Comment by regotto-xqk** [comment]
哥, 用 docker 镜像启动, 这个也需要改 cnd 吗

**Comment by hzxie** [comment]
要啊。如果你不改 那你要保证CDN的地址可访问。
